### ISSUE TITLE
vue-cli-service: not found

### ISSUE THREAD

**Issue by ArsDankeZik** [jordigoyanes/pinturillo3#2]
Básicamente me está saltando eso al ejecutar `npm run build` y no sé como solucionarlo bien. 
Hay que decir que soy nuevo en el mundo de node, vue, etc, por ende no tengo mucha noción, espero poder solventarlo. 

![image](https://user-images.githubusercontent.com/19938775/79027422-6a765800-7b8c-11ea-88b1-47ad9e6a31a2.png)

**Comment by kikis1034** [comment]
Debes isntalar primero las dependencias. Ve a la carpeta pinturillo y ejecuta **npm install** y luego en la carpeta frontend lo mismo: **npm install**.
Si te da error de permisos hazlo con sudo y el flag **unsafe-perm**. Es decir: **sudo npm install --unsafe-perm=true**
